---
default_install_hook_types: ["pre-commit", "pre-push"]
default_stages: ["commit", "push"]
minimum_pre_commit_version: 2.18.0
repos:
  # Security
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.4
    hooks:
      - id: gitleaks
  - repo: https://github.com/fabasoad/pre-commit-snyk
    rev: v0.6.2
    hooks:
      - id: snyk-iac
        stages: ["push"]
  - repo: https://github.com/fabasoad/pre-commit-grype
    rev: v0.6.0
    hooks:
      - id: grype-dir
        args:
          - --grype-args=--by-cve --fail-on=low
          - --hook-args=--log-level debug
        stages: ["push"]
  # Terraform
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.92.1
    hooks:
      - id: terraform_fmt
        stages: ["commit"]
      - id: terraform_tflint
        args:
          - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl
        stages: ["commit"]
      - id: terraform_validate
        stages: ["commit"]
  - repo: https://github.com/bridgecrewio/checkov
    rev: 3.2.217
    hooks:
      - id: checkov
        args: ["--quiet","--framework","terraform"]
        stages: ["push"]
  # Markdown
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.41.0
    hooks:
      - id: markdownlint-fix
        stages: ["commit"]
  # Shell
  - repo: https://github.com/openstack/bashate
    rev: 2.1.1
    hooks:
      - id: bashate
        args: ["-i", "E003,E006"]
        stages: ["commit"]
  # Other
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-executables-have-shebangs
        stages: ["commit"]
      - id: check-shebang-scripts-are-executable
        stages: ["commit"]
      - id: check-merge-conflict
      - id: check-json
        stages: ["push"]
      - id: check-yaml
        stages: ["push"]
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: no-commit-to-branch
        stages: ["commit"]
      - id: trailing-whitespace
