---
default_install_hook_types: ["pre-commit", "pre-push"]
default_stages: ["commit", "push"]
minimum_pre_commit_version: 2.18.0
repos:
  # Security
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.2
    hooks:
      - id: gitleaks
  - repo: https://github.com/fabasoad/pre-commit-snyk
    rev: v0.5.0
    hooks:
      - id: snyk-iac
        stages: ["push"]
  # Terraform
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.88.0
    hooks:
      - id: terraform_fmt
        stages: ["commit"]
      - id: terraform_tflint
        args:
          - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl
        stages: ["commit"]
      - id: terraform_validate
        stages: ["commit"]
  - repo: https://github.com/bridgecrewio/checkov
    rev: 3.2.28
    hooks:
      - id: checkov
        args: ["--quiet","--framework","terraform"]
        stages: ["push"]
  # Markdown
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.39.0
    hooks:
      - id: markdownlint-fix
        stages: ["commit"]
  # Shell
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.6
    hooks:
      - id: shellcheck
        stages: ["push"]
  # Other
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-merge-conflict
      - id: check-json
        stages: ["push"]
      - id: check-yaml
        stages: ["push"]
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: no-commit-to-branch
        stages: ["commit"]
      - id: trailing-whitespace
