---
name: Analysis

on:
  push:
    paths:
      - '**.tf'
jobs:
  checkov:
    runs-on: ubuntu-latest
    name: checkov-action
    steps:
      - uses: actions/checkout@v2
      - uses: bridgecrewio/checkov-action@master
        with:
          directory: ./terraform
          framework: terraform
          output_format: cli
          download_external_modules: true
